# Generated by Django 5.2.13 on 2026-04-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="notification_url",
            field=models.URLField(blank=True),
        ),
    ]
