# Generated by Django 5.2.13 on 2026-04-27 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apitest", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("ready", "就绪")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("method", models.CharField(default="GET", max_length=10)),
                ("path", models.CharField(max_length=500)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("body", models.TextField(blank=True)),
                ("script", models.TextField(blank=True)),
                ("last_run_status", models.CharField(max_length=10, null=True)),
                ("last_run_at", models.DateTimeField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_cases",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
